version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./faiss-stores:/app/faiss-stores
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "4.0"
        reservations:
          memory: 2G
          cpus: "1.0"
    restart: unless-stopped
    command: node --max-old-space-size=6144 server.js

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.25"
    restart: unless-stopped

volumes:
  redis_data:
